[workspace]
members = [
    "contracts/trusted-forwarder",
    "contracts/token-paymaster",
    "contracts/voucher-paymaster",
    "contracts/account-abstraction-wallet",
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
